import { RegistrationForm } from '@/widgets/auth';
import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
	title: 'Регистрация | Финкнижка',
	description: 'Generated by create next app',
};

export default function Registration() {
	return <RegistrationForm />;
}
