import { LoginForm } from '@/src/widgets/auth';
import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
	title: 'Авторизация | Финкнижка',
	description: 'Generated by create next app',
};

export default function Login() {
	return <LoginForm />;
}
